on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chrome: ['113.0.5672.63']
    name: Google Chrome ${{ matrix.chrome }}

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v2

      - name: Instalar o Chrome Driver
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Iniciar o servidor X virtual
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # opcional

      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Configurar vari치veis de ambiente para Maven
        run: |
          echo "export PATH=/usr/share/maven/bin:$PATH" >> $GITHUB_ENV
          echo "export MAVEN_HOME=/usr/share/maven" >> $GITHUB_ENV
          echo "export MAVEN_OPTS='-Xmx2g'" >> $GITHUB_ENV

      - name: Executar Teste
        run: mvn clean test -Dtest=**/*RunnerTest -Dbrowser=chrome

      - name: Gerar relat칩rio
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relat칩rio
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '${{ github.workspace }}/target/formatedreport'
