on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: [ '84.0', 'devedition-84.0b1', 'latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest' ]
    name: Firefox ${{ matrix.firefox }} sample

    steps:
      - name: Setup firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}

      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Configurar vari치veis de ambiente para Maven
        run: |
          echo "export PATH=/usr/share/maven/bin:$PATH" >> $GITHUB_ENV
          echo "export MAVEN_HOME=/usr/share/maven" >> $GITHUB_ENV
          echo "export MAVEN_OPTS='-Xmx2g'" >> $GITHUB_ENV

      - name: Run Test
        run: mvn clean test -Dtest=**/*RunnerTest -Dbrowser=firefox

      - name: Gerar relat칩rio
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relat칩rio
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Imprimir diret칩rio atual com asteriscos
        run: bash -c 'echo -e "**********************************************************\n$(pwd)\n**********************************************************"'